"""Check metadata embedding in frames"""
from PIL import Image
import piexif
import json
from pathlib import Path
import sys

def check_metadata(image_path):
    """Check if COLMAP and camera metadata is embedded"""
    print(f"\n=== Checking: {Path(image_path).name} ===")
    
    try:
        img = Image.open(image_path)
        exif_data = img.info.get('exif')
        
        if not exif_data:
            print("❌ NO EXIF data found")
            return False
        
        exif = piexif.load(exif_data)
        
        # Check UserComment (JSON metadata)
        comment_bytes = exif.get('Exif', {}).get(37510)  # UserComment
        if comment_bytes:
            try:
                comment_text = comment_bytes.decode('utf-8', errors='ignore')
                metadata = json.loads(comment_text)
                
                # Check for COLMAP position
                colmap_pos = metadata.get('colmap_position')
                if colmap_pos:
                    print(f"✅ COLMAP Position: ({colmap_pos['x']:.3f}, {colmap_pos['y']:.3f}, {colmap_pos['z']:.3f})")
                else:
                    print("❌ NO COLMAP position")
                
                # Check for camera orientation
                if 'yaw' in metadata:
                    print(f"✅ Camera Orientation: Yaw={metadata['yaw']:.1f}° Pitch={metadata['pitch']:.1f}° Roll={metadata['roll']:.1f}°")
                    print(f"   FOV: {metadata.get('h_fov', 'N/A')}°")
                
                print(f"   Generated by: {metadata.get('generated_by', 'N/A')}")
                print(f"   Source: {metadata.get('position_source', 'N/A')}")
                
                return True
                
            except json.JSONDecodeError:
                print(f"⚠️  UserComment exists but not JSON: {comment_text[:100]}")
                return False
        else:
            print("❌ NO UserComment found")
            
        # Check ImageDescription (legacy format)
        desc_bytes = exif.get('0th', {}).get(270)  # ImageDescription
        if desc_bytes:
            try:
                desc = desc_bytes.decode('utf-8', errors='ignore')
                print(f"   ImageDescription: {desc[:100]}")
            except:
                pass
        
        return False
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

if __name__ == "__main__":
    # Find latest test directory
    test_base = Path(r"C:\Users\Everton-PC\Documents\ARQUIVOS_TESTE")
    latest_test = sorted(test_base.glob("test_*"), key=lambda p: p.stat().st_ctime, reverse=True)[0]
    
    print(f"\n{'='*60}")
    print(f"Test Directory: {latest_test.name}")
    print(f"{'='*60}")
    
    # Check equirect frame
    print("\n--- EQUIRECTANGULAR FRAME ---")
    equirect = latest_test / "stage1_frames" / "0.png"
    if equirect.exists():
        check_metadata(str(equirect))
    else:
        print("❌ Equirect frame not found")
    
    # Check perspective frame
    print("\n--- PERSPECTIVE FRAME ---")
    perspectives_dir = latest_test / "stage2_perspectives"
    if perspectives_dir.exists():
        perspective_files = sorted(perspectives_dir.glob("*.png"))
        if perspective_files:
            check_metadata(str(perspective_files[0]))
        else:
            print("❌ No perspective frames found")
    else:
        print("❌ stage2_perspectives directory not found")
    
    print(f"\n{'='*60}\n")
