"""
Generate visual comparison of masking engine options
"""

import sys
from pathlib import Path

print("="*70)
print("360ToolKit - Masking Engine Options")
print("="*70)
print()
print("Stage 3: Masking Settings")
print()
print("Masking Engine: [Select engine...]")
print()
print("Available options:")
print()
print("  1. 🚀 YOLO (ONNX) - Fast & Lightweight")
print("     └─ NMS-free inference • 3-4x faster • CUDA accelerated")
print("     └─ Speed: 0.43s | Quality: 80-85% | Coverage: 22.8%")
print()
print("  2. 🔥 YOLO (PyTorch) - Full Featured")
print("     └─ Full-featured YOLO • PyTorch backend • Ultralytics")
print("     └─ Speed: 0.50s | Quality: 85-90% | Coverage: 23-24%")
print()
print("  3. ✨ SAM ViT-B - Best Quality")
print("     └─ Superior segmentation • Best edge precision")
print("     └─ Speed: 0.38s | Quality: High edges | Coverage: 37.8%")
print("     └─ ⚠️ NOT RECOMMENDED ALONE - includes too much background")
print()
print("  4. ⭐ YOLO+SAM Hybrid - Best Results (NEW! RECOMMENDED!)")
print("     └─ YOLO detection + SAM segmentation • Pixel-perfect edges")
print("     └─ Speed: 0.40s | Quality: 95-98% | Coverage: 23.2%")
print("     └─ ✅ BEST CHOICE for photogrammetry workflows")
print()
print("="*70)
print()
print("When to use each:")
print()
print("  YOLO ONNX:    Speed priority, good enough quality")
print("  YOLO PyTorch: Full features, custom training")
print("  SAM ViT-B:    Don't use alone (needs YOLO detection)")
print("  Hybrid:       Best quality + acceptable speed ← DEFAULT")
print()
print("="*70)
